### ISSUE TITLE
Try to edit an user, it crashes.

### ISSUE THREAD

**Issue by PatrickVChung** [OHSU-FM/reindeer#15]
The error is "undefined method 'lime_survey' for nil:Class

**Comment by hattwj** [comment]
Is this in the rails_admin interface? I am looking at it now and I am not able to reproduce the issue on the ohsu/master branch. I'll switch over to the feature branch and take a look there. Also, a stack trace would be excellent!

**Comment by hattwj** [comment]
I just checked on the feature/task branch and still haven't found the issue, though I have not created any surveys. Let me know if you have a reliable way to reproduce.

**Comment by wceichelb** [comment]
visit admin/user edit/show path with a nil `role_aggregate` 

app/views/rails_admin/main/users/_field_explain_survey_access.html.erb, line 13

`details, ra = permission_group.explain_role_aggregates_for(user)`, we then iterate over `ra` and call `ra.lime_survey.title`. if there are nil records in the `role_aggregate` table things blow up!

**Comment by wceichelb** [comment]
turns out the crash doesn't occur if there are nil `role_aggregate`s, but if there are `lime_survey`s that aren't assigned a `role_aggregate`.

**Comment by wceichelb** [comment]
a potential alternate fix would be to assign a default `role_aggregate` to each `lime_survey` on creation. just so `ra.lime_survey.title` points to something.

**Comment by hattwj** [comment]
I'll have to think about that. We can't trigger those without a 'database trigger' because they are created by lime. might be we just need some error handling. I'm hoping to look at it tonight.
