### ISSUE TITLE
controller_full_name helper method points to incorrect spot when used for ls_reports/* js/css

### ISSUE THREAD

**Issue by wceichelb** [OHSU-FM/reindeer#18]
### issue

in the ls_reports/filter view, the current implementation of controller_full_name--

<pre><code>
def controller_full_name
    controller.class.name.sub("Controller","").gsub("::","/").underscore
end
</code></pre>

outputs the controller name as `ls_reports/filter`. `stylesheet_link_tag` takes a string and looks for a css file with that name in the `assets/*` directory. the actual css file is `stylesheets/ls_reports_filter.scss`

### solution

take out that `/`, yo

this further solves the issue where the highcharts js wasn't loading in ls_reports/graph views.

**Comment by hattwj** [comment]
Nice! Up for a pull request?

**Comment by wceichelb** [comment]
tryna be meticulous on fork/issue/pull request cycle because i'm new to this open source/collaboration game

**Comment by hattwj** [comment]
One thing to note, I think I did the forward slash so that assets can have  sub directories. We might want to think about this one. Like nested controllers etc...

**Comment by wceichelb** [comment]
yeah i figured that was the intention, and i do agree on the sub directories point (there's some precedent in the rails_admin directory already), but as far as i can tell, `stylesheet_link_tag` will just looks for the file name recursively, so it'll find `stylesheets/ls_reports/ls_reports_filter.scss` just as easily as `stylesheets/ls_reports_filter.scss`. 

also, i briefly tried making a `ls_reports` directory and mv'ing `ls_reports_filter.css` to `ls_reports/filter.css`, but it blew up on me. i don't think stylesheet_link_tag likes `/`'s in its arguments
