### ISSUE TITLE
Move hattwj feature/tasks branch to OHSU

### ISSUE THREAD

**Issue by hattwj** [OHSU-FM/reindeer#35]

**Comment by wceichelb** [comment]
just in terms of imposing a pseudo-institutional structure on the project, maybe call it a release branch on OHSU?

**Comment by hattwj** [comment]
sounds good. Maybe something like release/assignments ?

**Comment by hattwj** [comment]
This is going to take a little bit of work as the branch has diverged from master and needs a rebase.

**Comment by hattwj** [comment]
Initial merge complete
