### ISSUE TITLE
Assignment Group: Controller

### ISSUE THREAD

**Issue by hattwj** [OHSU-FM/reindeer#36]
- [x] Strong parameters in controller, verify that only attributes required for update/create are allowed
- [x] Create unit test for controller for crud actions
- [ ] Verify that controller respects Abilities class restrictions (in unit test)

**Comment by wceichelb** [comment]
the last task should be on the assignment group comments controller issue, shouldn't it?

**Comment by hattwj** [comment]
++ Very true

**Comment by wceichelb** [comment]
first two done as of commit 61fb755 in release/coaching
